package com.imagesys.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class ImageInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.id
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.imageName
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private String imagename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.imageSize
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private BigDecimal imagesize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.updateDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.devId
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long devid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.imageInfo
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private String imageinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.status
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.onSaleDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Date onsaledate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.OffSaleDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Date offsaledate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.categoryLevel1
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long categorylevel1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.categoryLevel2
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long categorylevel2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.categoryLevel3
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long categorylevel3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.downloads
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long downloads;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.imagePicPath
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private String imagepicpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.imageLocPath
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private String imagelocpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.createdBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.creationDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.modifyBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long modifyby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.modifyDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Date modifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.id
     *
     * @return the value of image_info.id
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.id
     *
     * @param id the value for image_info.id
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.imageName
     *
     * @return the value of image_info.imageName
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public String getImagename() {
        return imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.imageName
     *
     * @param imagename the value for image_info.imageName
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setImagename(String imagename) {
        this.imagename = imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.imageSize
     *
     * @return the value of image_info.imageSize
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public BigDecimal getImagesize() {
        return imagesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.imageSize
     *
     * @param imagesize the value for image_info.imageSize
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setImagesize(BigDecimal imagesize) {
        this.imagesize = imagesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.updateDate
     *
     * @return the value of image_info.updateDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.updateDate
     *
     * @param updatedate the value for image_info.updateDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.devId
     *
     * @return the value of image_info.devId
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getDevid() {
        return devid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.devId
     *
     * @param devid the value for image_info.devId
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setDevid(Long devid) {
        this.devid = devid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.imageInfo
     *
     * @return the value of image_info.imageInfo
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public String getImageinfo() {
        return imageinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.imageInfo
     *
     * @param imageinfo the value for image_info.imageInfo
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setImageinfo(String imageinfo) {
        this.imageinfo = imageinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.status
     *
     * @return the value of image_info.status
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.status
     *
     * @param status the value for image_info.status
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.onSaleDate
     *
     * @return the value of image_info.onSaleDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Date getOnsaledate() {
        return onsaledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.onSaleDate
     *
     * @param onsaledate the value for image_info.onSaleDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setOnsaledate(Date onsaledate) {
        this.onsaledate = onsaledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.OffSaleDate
     *
     * @return the value of image_info.OffSaleDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Date getOffsaledate() {
        return offsaledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.OffSaleDate
     *
     * @param offsaledate the value for image_info.OffSaleDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setOffsaledate(Date offsaledate) {
        this.offsaledate = offsaledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.categoryLevel1
     *
     * @return the value of image_info.categoryLevel1
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getCategorylevel1() {
        return categorylevel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.categoryLevel1
     *
     * @param categorylevel1 the value for image_info.categoryLevel1
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setCategorylevel1(Long categorylevel1) {
        this.categorylevel1 = categorylevel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.categoryLevel2
     *
     * @return the value of image_info.categoryLevel2
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getCategorylevel2() {
        return categorylevel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.categoryLevel2
     *
     * @param categorylevel2 the value for image_info.categoryLevel2
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setCategorylevel2(Long categorylevel2) {
        this.categorylevel2 = categorylevel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.categoryLevel3
     *
     * @return the value of image_info.categoryLevel3
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getCategorylevel3() {
        return categorylevel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.categoryLevel3
     *
     * @param categorylevel3 the value for image_info.categoryLevel3
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setCategorylevel3(Long categorylevel3) {
        this.categorylevel3 = categorylevel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.downloads
     *
     * @return the value of image_info.downloads
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getDownloads() {
        return downloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.downloads
     *
     * @param downloads the value for image_info.downloads
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setDownloads(Long downloads) {
        this.downloads = downloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.imagePicPath
     *
     * @return the value of image_info.imagePicPath
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public String getImagepicpath() {
        return imagepicpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.imagePicPath
     *
     * @param imagepicpath the value for image_info.imagePicPath
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setImagepicpath(String imagepicpath) {
        this.imagepicpath = imagepicpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.imageLocPath
     *
     * @return the value of image_info.imageLocPath
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public String getImagelocpath() {
        return imagelocpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.imageLocPath
     *
     * @param imagelocpath the value for image_info.imageLocPath
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setImagelocpath(String imagelocpath) {
        this.imagelocpath = imagelocpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.createdBy
     *
     * @return the value of image_info.createdBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.createdBy
     *
     * @param createdby the value for image_info.createdBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.creationDate
     *
     * @return the value of image_info.creationDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.creationDate
     *
     * @param creationdate the value for image_info.creationDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.modifyBy
     *
     * @return the value of image_info.modifyBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.modifyBy
     *
     * @param modifyby the value for image_info.modifyBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setModifyby(Long modifyby) {
        this.modifyby = modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.modifyDate
     *
     * @return the value of image_info.modifyDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.modifyDate
     *
     * @param modifydate the value for image_info.modifyDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }
}