package com.imagesys.pojo;

import java.util.Date;

public class ImageVersion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_version.id
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_version.imageId
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long imageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_version.publishStatus
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long publishstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_version.downloadLink
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private String downloadlink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_version.imageLocPath
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private String imagelocpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_version.imageFileName
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private String imagefilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_version.createdBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_version.creationDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_version.modifyBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long modifyby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_version.modifyDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Date modifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_version.id
     *
     * @return the value of image_version.id
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_version.id
     *
     * @param id the value for image_version.id
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_version.imageId
     *
     * @return the value of image_version.imageId
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getImageid() {
        return imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_version.imageId
     *
     * @param imageid the value for image_version.imageId
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setImageid(Long imageid) {
        this.imageid = imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_version.publishStatus
     *
     * @return the value of image_version.publishStatus
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getPublishstatus() {
        return publishstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_version.publishStatus
     *
     * @param publishstatus the value for image_version.publishStatus
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setPublishstatus(Long publishstatus) {
        this.publishstatus = publishstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_version.downloadLink
     *
     * @return the value of image_version.downloadLink
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public String getDownloadlink() {
        return downloadlink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_version.downloadLink
     *
     * @param downloadlink the value for image_version.downloadLink
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setDownloadlink(String downloadlink) {
        this.downloadlink = downloadlink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_version.imageLocPath
     *
     * @return the value of image_version.imageLocPath
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public String getImagelocpath() {
        return imagelocpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_version.imageLocPath
     *
     * @param imagelocpath the value for image_version.imageLocPath
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setImagelocpath(String imagelocpath) {
        this.imagelocpath = imagelocpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_version.imageFileName
     *
     * @return the value of image_version.imageFileName
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public String getImagefilename() {
        return imagefilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_version.imageFileName
     *
     * @param imagefilename the value for image_version.imageFileName
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setImagefilename(String imagefilename) {
        this.imagefilename = imagefilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_version.createdBy
     *
     * @return the value of image_version.createdBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_version.createdBy
     *
     * @param createdby the value for image_version.createdBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_version.creationDate
     *
     * @return the value of image_version.creationDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_version.creationDate
     *
     * @param creationdate the value for image_version.creationDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_version.modifyBy
     *
     * @return the value of image_version.modifyBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_version.modifyBy
     *
     * @param modifyby the value for image_version.modifyBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setModifyby(Long modifyby) {
        this.modifyby = modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_version.modifyDate
     *
     * @return the value of image_version.modifyDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_version.modifyDate
     *
     * @param modifydate the value for image_version.modifyDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }
}