package com.imagesys.pojo;

import java.util.Date;

public class ImageCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_category.id
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_category.categoryCode
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private String categorycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_category.categoryName
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private String categoryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_category.parentId
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_category.createdBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_category.creationDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_category.modifyBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Long modifyby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_category.modifyDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    private Date modifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_category.id
     *
     * @return the value of image_category.id
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_category.id
     *
     * @param id the value for image_category.id
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_category.categoryCode
     *
     * @return the value of image_category.categoryCode
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public String getCategorycode() {
        return categorycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_category.categoryCode
     *
     * @param categorycode the value for image_category.categoryCode
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setCategorycode(String categorycode) {
        this.categorycode = categorycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_category.categoryName
     *
     * @return the value of image_category.categoryName
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_category.categoryName
     *
     * @param categoryname the value for image_category.categoryName
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_category.parentId
     *
     * @return the value of image_category.parentId
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_category.parentId
     *
     * @param parentid the value for image_category.parentId
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_category.createdBy
     *
     * @return the value of image_category.createdBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_category.createdBy
     *
     * @param createdby the value for image_category.createdBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_category.creationDate
     *
     * @return the value of image_category.creationDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_category.creationDate
     *
     * @param creationdate the value for image_category.creationDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_category.modifyBy
     *
     * @return the value of image_category.modifyBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Long getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_category.modifyBy
     *
     * @param modifyby the value for image_category.modifyBy
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setModifyby(Long modifyby) {
        this.modifyby = modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_category.modifyDate
     *
     * @return the value of image_category.modifyDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_category.modifyDate
     *
     * @param modifydate the value for image_category.modifyDate
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }
}