package com.imagesys.mapper;

import com.imagesys.pojo.BackendUser;

public interface BackendUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    int insert(BackendUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    int insertSelective(BackendUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    BackendUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    int updateByPrimaryKeySelective(BackendUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    int updateByPrimaryKey(BackendUser record);
}