package com.imagesys.mapper;

import com.imagesys.pojo.ImageCategory;

public interface ImageCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_category
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_category
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    int insert(ImageCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_category
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    int insertSelective(ImageCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_category
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    ImageCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_category
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    int updateByPrimaryKeySelective(ImageCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_category
     *
     * @mbggenerated Tue Jul 14 11:46:22 CST 2020
     */
    int updateByPrimaryKey(ImageCategory record);
}